### PR TITLE
Added in .htaccess for apache servers

### PR DESCRIPTION
**Pull request by outrunthewolf**
Should have tested this earlier, only just got a chance

### CODE REVIEW

**Comment by scottrobertson** [comment]
I forgot about Apache :+1: 

@marcqualie would you do this here or have them configure it at server level?

**Comment by marcqualie** [comment]
No harm having it here, people are lazy.

**Comment by scottrobertson** [comment]
I agree, people are lazy :shipit:

**Comment by outrunthewolf** [comment]
where "people" read Marc Qualie

**Pull request merged**
