### PR TITLE
Shifting to require js, allowing better future support for MVVM

### PR DESCRIPTION
**Pull request by outrunthewolf**
I think its all working, point any bugs back to me if you have issues and i'll fix them. :)

### CODE REVIEW

**Comment by marcqualie** [comment]
Don't think this is realated to your changes but I get

```
Fatal error: Uncaught exception 'Exception' with message 'MongoDB::__construct(): invalid name ' in /opt/criterion/vendor/marcqualie/mongominify/lib/MongoMinify/Db.php on line 18
```

I assume this is because I've never setup my config, we should have a helpful message here?

**Edit:** I get the same error when running the installer, I can't do anything..

**Comment by marcqualie** [comment]
I've just pushed a fix to master, merge that into this branch and it should fix it. 59983151ab5a2fb0fc3051f6a0ebca123199eb14

**Comment by scottrobertson** [comment]
I did think adding Mongo to the config.json would cause a few issues, just thought id got them all.

**Comment by marcqualie** [comment]
I've moved this to a feature branch on #53

**Pull request closed without merging**
