### PR TITLE
Feature/none basic auth

### PR DESCRIPTION
**Pull request by scottrobertson**

### CODE REVIEW

**Comment by scottrobertson** [comment]
Can this be tested. You will need to purge users collection.

**Comment by marcqualie** [comment]
Anything can be tested, purging the user collection is what should happen anyways. Each test should have it's own fresh data set, unless it's an end-to-end test in which case you'll want to chain them with dependencies.

ONe more thing, what made you change from using _id as the username? The advantage here is it's already indexed and there's not two unique identifiers per user.

**Comment by scottrobertson** [comment]
Yeah i worded that wrong, i just meant can someone test it :page_facing_up: 

I changed it because of what i explained last night, with passing a string into the model, it kinda breaks a little, but i think i know a way of making it work. I shall get this changed back tonight.

**Comment by marcqualie** [comment]
I'll try and write some tests up for this, everything should be fully unit tested before going into master. How ironic that  CI tool wasn't tested properly before being merged ;)

Ah yeah I remember now, you and your sketchy models! :P The fix is easy, dont' always assume the ID is a MongoId.

**Comment by scottrobertson** [comment]
Yeah, i was going to try and write a few unit tests for it before pushing it into master. Not had a chance yet though.

And yeah, my models :P

**Comment by scottrobertson** [comment]
Is this good to merge? @marcqualie @outrunthewolf

**Pull request merged**
